name: CI Test

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Test
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm run test:ci
